<template>
  <v-container>
    <!-- <hr> -->
    <v-row>
      <img
        src="../assets/ImageHeadInjury.png"
        alt="Head Injury"
        height="32px"
        class="mt-2"
      />

      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/headinjury')"
        >
          Head Injury
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/headinjury-no-ct')"
        >
          Head Injury No CT
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/concussion')"
        >
          Concussion
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/nonaccidental')"
        >
          Non-Accidental
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="grey"
          size="small"
          @click="openDialog('/pediheadinjuryalgorithm')"
        >
          Pedi TBI Algorithm
        </v-btn>
      </v-col>
      <v-col>
        <v-btn color="grey" size="small" @click="openDialog('/severeTBI')">
          Severe TBI
        </v-btn>
      </v-col>
    </v-row>

    <hr />

    <v-row class="small-vertical">
      <img src="../assets/eye.png" alt="eye" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/sty')"
        >
          Sty
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/conjunctivitis')"
        >
          Conjunctivitis
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/eyefb')"
        >
          Eye FB
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/abrasion')"
        >
          Abrasion
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/cornealulcer')"
        >
          Corneal Ulcer
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/blurry')"
        >
          Blurry
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/notglaucoma')"
        >
          Not Glaucoma
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/subconjunctivalhemorrhage')"
        >
          Subconjunctival Hemorrhage
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img
        class="mt-3"
        height="32px"
        src="../assets/faceInjury.png"
        alt="faceInjury"
      />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/facialinjury')"
        >
          Facial Injury
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/nasalinjury')"
        >
          Nasal Injury
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/DentalInjury')"
        >
          Dental Injury
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img
        class="mt-3"
        height="32px"
        src="../assets/neckUpperBack.png"
        alt="Neck & Upper Back"
      />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/cervicalradiculopathy')"
          >Cervical Radiculopathy</v-btn
        >
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/trapeziusspasm')"
          >Trapezius Spasm</v-btn
        >
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/neckpain')"
          >Neck Pain</v-btn
        >
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/upperback')"
          >Upper Back</v-btn
        >
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/upperbackinjury')"
          >Upper Back Injury</v-btn
        >
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img
        class="mt-3"
        height="32px"
        src="../assets/shoulder.png"
        alt="Shoulder"
      />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/shouldersprain')"
        >
          Shoulder Sprain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/rotatorcuff')"
          >Rotator Cuff
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/shoulderbruise')"
          >Shoulder Contusion
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/arthritis')"
          >arthritis
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/acseparation')"
          >AC Separation
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/claviclefx')"
          >clavicle fx
        </v-btn>
      </v-col>

      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/proximalhumerusfx')"
        >
          Prox Humerus FX
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/elbowfx')"
        >
          Elbow FX
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img class="mt-3" src="../assets/arm.png" alt="arm" />
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/injurymild')"
        >
          injury mild
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/wristfx')"
        >
          wrist fx
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/wristsprain')"
        >
          wrist sprain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/bursitis')"
        >
          bursitis
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/laceration')"
        >
          laceration
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img
        class="mt-3"
        height=" 32px"
        src="../assets/ChestWall.png"
        alt="chestwall"
      />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/chesttrauma')"
        >
          chest trauma
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img class="mt-3" height="32px" src="../assets/back.png" alt="" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/backpain')"
        >
          back pain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/thoracicbackpain')"
        >
          thoracic back pain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/backinjury')"
        >
          back injury
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/pilonidalcyst')"
        >
          pilonidal cyst
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img class="mt-3" height="32px" src="../assets/hand.png" alt="hand" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/paronychia')"
        >
          Paronychia
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/thumbsprain')"
        >
          Thumb Sprain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/kanaval')"
        >
          kanavel
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/fingeramputation')"
        >
          Finger amputation
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/fingerfx')"
        >
          finger fx
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/boxerfx')"
        >
          boxer fx
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/wristfx')"
        >
          Wrist fx
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/nailavulsion')"
        >
          Nail Avulsion
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/trephination')"
        >
          trephination
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img class="mt-3" height="32px" src="../assets/hip.png" alt="" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/sciatica')"
        >
          sciatica
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/contusion')"
        >
          contusion
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/hipsprain')"
        >
          hip sprain
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img class="mt-3" height="32px" src="../assets/knee.png" alt="" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/kneesprain')"
        >
          knee sprain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/compartmentsyndrome')"
        >
          not Compartment Syndrome
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/leginjury')"
        >
          leg Injury
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/kneeeffusion')"
        >
          knee effusion
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/legpain')"
        >
          Leg Pain
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img class="mt-3" height="32px" src="../assets/ankle.png" alt="" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/anklesprain')"
        >
          Ankle Sprain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/achillestendonitis')"
        >
          achilles Tendonitis
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/anklefx')"
        >
          ankle fx
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/conscioussedation')"
        >
          conscious sedation
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img class="mt-3" height="32px" src="../assets/foot.png" alt="" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/footpuncture')"
        >
          foot puncture
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/fbnoremoval')"
        >
          FB NO removal
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/fbremoval')"
        >
          FB + removal
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/footpain')"
        >
          foot pain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/footsprain')"
        >
          foot sprain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/footfx')"
        >
          foot fx
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/gout')"
        >
          gout
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/footparesthesia')"
        >
          foot paresthesia
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/paronychia')"
        >
          paronychia
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/toefx')"
        >
          toe fx
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img class="mt-3" height="32px" src="../assets/car.png" alt="mvc" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/MVC')"
        >
          motor vehicle collision
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/majortrauma')"
        >
          Major Trauma
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/fall')"
        >
          fall
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/daterape')"
        >
          Date rape
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/packingremoved')"
        >
          Packing removed
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/postsurgicalwound')"
        >
          Post surgical wound
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="warning"
          size="small"
          rounded="xl"
          @click="openDialog('/packingchange')"
        >
          packing change
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img src="../assets/fire.png" alt="fire" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/burn')"
        >
          burn
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/inhalationinjury')"
        >
          inhalation injury
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img src="../assets/bite.png" alt="bite" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/animalbite')"
        >
          animal bite
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/insectbite')"
        >
          insect bite
        </v-btn>
      </v-col>
    </v-row>
    <hr style="border-top: 5px solid white" />
    <v-row>
      <img src="../assets/head.png" alt="head" height="32px" class="mt-3" />

      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/headache')"
        >
          Headache
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/migraine')"
        >
          Migraine
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/notpreEclampsia')"
        >
          Not Pre-eclampsia
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/hypertension')"
        >
          hypertension
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img src="../assets/ear.png" alt="ear" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/earfb')"
        >
          Ear FB
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/otitismedia')"
        >
          Otitis Media
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/otitisexterna')"
        >
          Otitis Externa
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/cerumenimpaction')"
        >
          cerumen impaction
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/perforation')"
        >
          perforation
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img src="../assets/nose.png" alt="nose" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/nosefb')"
        >
          Nose FB
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/epistaxis')"
        >
          Epistaxis
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img src="../assets/mouth.png" alt="mouth" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/sorethroat')"
        >
          Sore Throat
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/toothache')"
        >
          Toothache
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/pharyngealscratch')"
        >
          Pharyngeal Scratch
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/pharyngealcellulitis')"
        >
          Pharyngeal Cellulitis
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/preseptalcellulitis')"
        >
          Preseptal Cellulitis
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/coldsore')"
        >
          Cold Sore
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/mono')"
        >
          mono
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/tmj')"
        >
          tmj
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img src="../assets/virus.png" alt="virus" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/uri')"
        >
          URI
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/sinusitis')"
        >
          Sinusitis
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/bronchitis')"
        >
          Bronchitis
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/flu')"
        >
          Flu
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/covid')"
        >
          Covid
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/cough')"
        >
          cough
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/allergicrhinitis')"
        >
          Allergic Rhinitis
        </v-btn>
      </v-col>
    </v-row>
    <hr />
    <v-row>
      <img src="../assets/lung.png" alt="lung" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/dyspnea')"
        >
          dyspnea
        </v-btn>
      </v-col>

      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/asthma')"
        >
          asthma
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/copd')"
        >
          copd
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/pneumonia')"
        >
          pneumonia
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/hiccups')"
        >
          hiccups
        </v-btn>
      </v-col>
    </v-row>
    <hr>
    <v-row>
<img src="../assets/heart.png" alt="heart" height="32px" class="mt-3" />
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/chestpain')"
        >
          Chest Pain
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/chestpainadmission')"
        >
          Chest pain admission
        </v-btn>
      </v-col>

      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/pleurisy')"
        >
          pleurisy
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/palpitations')"
        >
          Palpitations
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          color="primary"
          size="small"
          rounded="xl"
          @click="openDialog('/bradycardia')"
        >
          bradycardia
        </v-btn>
      </v-col>
    </v-row>
    <hr>
<v-row>
  <img src="../assets/abdomen.png" alt="abdomen" class = "mt-3" height="32px"/>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/femaleabdominalpain')"
    >
      ♀ Gen Abd pain
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/maleabdominalpain')"
    >
      ♂ Gen Abd pain
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/constipation')"
    >
      constipation
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/diverticulitis')"
    >
      diverticulitis
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/biliarycolic')"
    >
      Biliary Colic
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/kidneystone')"
    >
      Kidney Stone
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/pyelonephritis')"
    >
     Pyelonephritis
    </v-btn>
  </v-col>
  <v-col>
        <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/colitis')"
    >
     colitis
    </v-btn>
  </v-col>
</v-row>
<hr>
<v-row>
  <img src="../assets/vomit.png" alt="vomit" class = "mt-3" height="32px"/>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/age')"
    >
      age
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/diarrhea')"
    >
      diarrhea
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/gastritis')"
    >
      gastritis
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/gerd')"
    >
      gerd
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/hyperemesisgravidarum')"
    >
      hyperemesis gravidarum
    </v-btn>
  </v-col>
</v-row>
<hr>
<v-row>
  <img src="../assets/butt.png" alt="butt" class = "mt-3" height="32px"/>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/pilonidalcyst')"
    >
      pilonidal cyst
    </v-btn>

  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/hematochezia')"
    >
      hematochezia
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/perianal')"
    >
      peri-anal
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/rectalfissure')"
    >
      rectal fissure
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/hemorrhoid')"
    >
      Hemorrhoid
    </v-btn>
  </v-col>
</v-row>
<hr>
<v-row>
<img src="../assets/uterus.png" alt="uterus" class = "mt-3" height="32px"/>
 <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/uti')"
    >
      uti
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/femalestd')"
    >
     STD ♀
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/dysmenorrhea')"
    >
      Dysmenorrhea
    </v-btn>
  </v-col>
  <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/threatmiscarriage')"
    >
      threat misc
    </v-btn>
  </v-col>
 <v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/ovariancyst')"
    >
      Ovar Cyst 
    </v-btn>
  </v-col>
<v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/bartholins')"
    >
      bartholins
    </v-btn>
  </v-col>
<v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/herpes')"
    >
      Herpes
    </v-btn>

  </v-col>
<v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/pregnancypain')"
    >
      pregnancy pain
    </v-btn>
  </v-col>
<v-col>   
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/vaginitis')"
    >
      Vaginitis
    </v-btn>
  </v-col>

<v-col>
    <v-btn
      color="primary"
      size="small"
      rounded="xl"
      @click="openDialog('/notectopicpregnancy')"
    >
      not EP    </v-btn>
  </v-col>


</v-row>
  </v-container>
</template>

<script>
export default {
  name: "HomeView",
  data() {
    return {
      showRouterView: false,
      dialogRoutes: [
        "/headinjury",
        "/headinjury-no-ct",
        "/concussion",
        "/nonaccidental",
        "/pediheadinjuryalgorithm",
        "/severeTBI",
        "/sty",
        "/conjunctivitis",
        "/eyefb",
        "/abrasion",
        "/cornealulcer",
        "/blurry",
        "/notglaucoma",
        "/subconjunctivalhemorrhage",
        "/facialinjury",
        "/nasalinjury",
        "/DentalInjury",
        "/cervicalradiculopathy",
        "/trapeziusspasm",
        "/neckpain",
        "/upperback",
        "/upperbackinjury",
        "/shouldersprain",
        "/rotatorcuff",
        "/shoulderbruise",
        "/arthritis",
        "/acseparation",
        "/claviclefx",
        "/proximalhumerusfx",
        "/elbowfx",
        "/injurymild",
        "/wristfx",
        "/wristsprain",
        "/bursitis",
        "/laceration",
        "/chesttrauma",
        "/backpain",
        "/thoracicbackpain",
        "/backinjury",
        "/pilonidalcyst",
        "/paronychia",
        "/thumbsprain",
        "/kanaval",
        "/fingeramputation",
        "/fingerfx",
        "/boxerfx",
        "/nailavulsion",
        "/trephination",
        "/sciatica",
        "/contusion",
        "/hipsprain",
        "/kneesprain",
        "/compartmentsyndrome",
        "/leginjury",
        "/kneeeffusion",
        "/legpain",
        "/anklesprain",
        "/achillestendonitis",
        "/anklefx",
        "/conscioussedation",
        "/footpuncture",
        "/fbnoremoval",
        "/fbremoval",
        "/footpain",
        "/footsprain",
        "/footfx",
        "/gout",
        "/footparesthesia",
        "/toefx",
        "/mvc",
        "/majortrauma",
        "/fall",
        "/daterape",
        "/packingremoved",
        "/postsurgicalwound",
        "/packingchange",
        "/burn",
        "/inhalationinjury",
        "/animalbite",
        "/insectbite",
        "/headache",
        "/migraine",
        "/notpreEclampsia",
        "/hypertension",
        "/earfb",
        "/otitismedia",
        "/otitisexterna",
        "/cerumenimpaction",
        "/perforation",
        "/nosefb",
        "/epistaxis",
        "/sorethroat",
        "/toothache",
        "/pharyngealscratch",
        "/pharyngealcellulitis",
        "/preseptalcellulitis",
        "/coldsore",
        "/mono",
        "/tmj",
        "/uri",
        "/sinusitis",
        "/bronchitis",
        "/flu",
        "/covid",
        "/cough",
        "/allergicrhinitis",
        "/dyspnea",
        "/asthma",
        "/copd",
        "/pneumonia",
        "/hiccups",
        "/chestpain",
        "/chestpainadmission",
        "/pleurisy",
        "/palpitations",
        "/bradycardia",
        "/femaleabdominalpain",
        "/maleabdominalpain",
        "/constipation",
        "/diverticulitis",
        "/biliarycolic",
        "/kidneystone",
        "/pyelonephritis",
        "/colitis",
        "/age",
        "/diarrhea",
        "/gastritis",
        "/gerd",
        "/hyperemesisgravidarum",
        "/hematochezia",
        "/perianal",
        "/rectalfissure",
        "/hemorrhoid",
        "/uti",
        "/femalestd",
        "/dysmenorrhea",
      ],
    };
  },

  methods: {
    openDialog(route) {
      this.$router.push(route);
    },
    closeDialog() {
      this.showRouterView = false;
      this.$router.push("/");
    },
  },
  watch: {
    $route(to) {
      this.showRouterView = this.dialogRoutes.includes(to.path);
    },
  },
};
</script>